.TH "Sourcecode/main.py" 3 "Fri Jan 19 2024 15:50:52" "Version 1.0.0" "IC: Icon Creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sourcecode/main.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\&.resize_image\fP (image, size)"
.br
.ti -1c
.RI "\fBmain\&.convert_to_pil\fP (image)"
.br
.ti -1c
.RI "\fBmain\&.save_image\fP (image_pil, filename, image_format, folder)"
.br
.ti -1c
.RI "\fBmain\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain\&.message\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IC: Icon Creator from the source code\&.
